name: android_id
description: A Flutter plugin for getting the Android ID.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: plus.fluttercommunity.dev.android_id
        pluginClass: AndroidIdPlugin
 